DROP POLICY IF EXISTS "Admin can manage all notifications" ON "public"."notifications";
DROP POLICY IF EXISTS "Admin can manage roles" ON "public"."roles";
DROP POLICY IF EXISTS "Admin can manage user roles" ON "public"."user_roles";
DROP POLICY IF EXISTS "Admin can view audit logs" ON "public"."audit_logs";
DROP POLICY IF EXISTS "Admin full access to profiles" ON "public"."profiles";
DROP POLICY IF EXISTS "Admin full access to roles" ON "public"."roles";
DROP POLICY IF EXISTS "Admin full access to stock movements" ON "public"."stock_movements";
DROP POLICY IF EXISTS "Admin full access to user_roles" ON "public"."user_roles";
DROP POLICY IF EXISTS "Allow managers and admins to manage discount configs" ON "public"."discount_configs";
DROP POLICY IF EXISTS "Cash sessions deletable by Admin/Mgr" ON "public"."cash_sessions";
DROP POLICY IF EXISTS "Cash sessions insertable by Admin/Mgr or Cashier" ON "public"."cash_sessions";
DROP POLICY IF EXISTS "Cash sessions mutable by Admin/Mgr or Cashier Own" ON "public"."cash_sessions";
DROP POLICY IF EXISTS "Cash sessions viewable by Admin/Mgr/Cashier" ON "public"."cash_sessions";
DROP POLICY IF EXISTS "Cash transactions deletable by Admin/Mgr" ON "public"."cash_transactions";
DROP POLICY IF EXISTS "Cash transactions insertable by Admin/Mgr/Cashier" ON "public"."cash_transactions";
DROP POLICY IF EXISTS "Cash transactions mutable by Admin/Mgr" ON "public"."cash_transactions";
DROP POLICY IF EXISTS "Cash transactions viewable by Admin/Mgr/Cashier" ON "public"."cash_transactions";
DROP POLICY IF EXISTS "Cashier can add expenses" ON "public"."expenses";
DROP POLICY IF EXISTS "Categories managed by Admin/Mgr/Inv (Delete)" ON "public"."categories";
DROP POLICY IF EXISTS "Categories managed by Admin/Mgr/Inv (Insert)" ON "public"."categories";
DROP POLICY IF EXISTS "Categories managed by Admin/Mgr/Inv (Update)" ON "public"."categories";
DROP POLICY IF EXISTS "Daily inventory insert by authorized" ON "public"."daily_inventory_periods";
DROP POLICY IF EXISTS "Daily inventory lines deletable by authorized" ON "public"."daily_inventory_lines";
DROP POLICY IF EXISTS "Daily inventory lines mutable by authorized" ON "public"."daily_inventory_lines";
DROP POLICY IF EXISTS "Daily inventory lines updatable by authorized" ON "public"."daily_inventory_lines";
DROP POLICY IF EXISTS "Daily inventory update" ON "public"."daily_inventory_periods";
DROP POLICY IF EXISTS "Discounts deletable by Admin/Mgr/Cashier" ON "public"."discounts";
DROP POLICY IF EXISTS "Discounts insertable by Admin/Mgr/Cashier" ON "public"."discounts";
DROP POLICY IF EXISTS "Discounts updatable by Admin/Mgr/Cashier" ON "public"."discounts";
DROP POLICY IF EXISTS "Expense categories deletable by Admin/Mgr" ON "public"."expense_categories";
DROP POLICY IF EXISTS "Expense categories insertable by Admin/Mgr" ON "public"."expense_categories";
DROP POLICY IF EXISTS "Expense categories updatable by Admin/Mgr" ON "public"."expense_categories";
DROP POLICY IF EXISTS "Expenses managed by Admin/Mgr" ON "public"."expenses";
DROP POLICY IF EXISTS "Inventory balances insert by Admin/Mgr/Inv" ON "public"."inventory_balances";
DROP POLICY IF EXISTS "Locations managed by Admin/Mgr" ON "public"."inventory_locations";
DROP POLICY IF EXISTS "Purchase lines managed by Admin/Mgr/Inv" ON "public"."purchase_lines";
DROP POLICY IF EXISTS "Purchases managed by Admin/Mgr/Inv" ON "public"."purchases";
DROP POLICY IF EXISTS "Sale lines managed by Admin/Mgr/Cashier" ON "public"."sale_lines";
DROP POLICY IF EXISTS "Sales managed by Admin/Mgr/Cashier" ON "public"."sales";
DROP POLICY IF EXISTS "Stock items managed by Admin/Mgr/Inv" ON "public"."stock_items";
DROP POLICY IF EXISTS "Stock movements insertable by Admin/Mgr/Inv" ON "public"."stock_movements";
DROP POLICY IF EXISTS "Stock transfer lines managed by Admin/Mgr/Inv" ON "public"."stock_transfer_lines";
DROP POLICY IF EXISTS "Stock transfers managed by Admin/Mgr/Inv" ON "public"."stock_transfers";
DROP POLICY IF EXISTS "Supplier discounts managed by Admin/Mgr" ON "public"."supplier_discount_policies";
DROP POLICY IF EXISTS "Suppliers managed by Admin/Mgr/Inv" ON "public"."suppliers";
DROP POLICY IF EXISTS "Units managed by Admin/Mgr/Inv" ON "public"."units_of_measure";
CREATE POLICY "Enable all operations for authenticated users" ON "public"."stock_movements" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."discount_configs" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."cash_sessions" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."cash_transactions" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."expenses" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."categories" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."daily_inventory_periods" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."daily_inventory_lines" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."discounts" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."expense_categories" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."inventory_balances" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."inventory_locations" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."purchase_lines" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."purchases" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."sale_lines" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."sales" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."stock_items" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."stock_transfer_lines" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."stock_transfers" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."supplier_discount_policies" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."suppliers" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for authenticated users" ON "public"."units_of_measure" FOR ALL TO authenticated USING (true) WITH CHECK (true);