-- Helper function to check if current user is ADMIN
CREATE OR REPLACE FUNCTION public.is_admin() RETURNS BOOLEAN AS $$
BEGIN
  RETURN (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'ADMIN';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-----------------------------------------------------------
-- 1. PROFILES
-----------------------------------------------------------
CREATE POLICY "Anyone can read profiles" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Users can update own display_name" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
-- Admins can update roles (we could add a specific admin policy for updates)
CREATE POLICY "Admins can update profiles" ON public.profiles FOR UPDATE USING (public.is_admin());

-----------------------------------------------------------
-- 2. CATEGORIES & 3. INVENTORY ITEMS (Master Data)
-----------------------------------------------------------
CREATE POLICY "Anyone can read categories" ON public.categories FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can insert categories" ON public.categories FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admins can update categories" ON public.categories FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admins can delete categories" ON public.categories FOR DELETE USING (public.is_admin());

CREATE POLICY "Anyone can read inventory_items" ON public.inventory_items FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can insert inventory_items" ON public.inventory_items FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admins can update inventory_items" ON public.inventory_items FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admins can delete inventory_items" ON public.inventory_items FOR DELETE USING (public.is_admin());

-----------------------------------------------------------
-- 4. STOCK BATCHES & 5. STOCK MOVEMENTS (Live Stock)
-----------------------------------------------------------
-- NOTE: Mutations are handled by SECURITY DEFINER RPCs. Users CANNOT directly INSERT/UPDATE/DELETE.
CREATE POLICY "Anyone can read stock_batches" ON public.stock_batches FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read stock_movements" ON public.stock_movements FOR SELECT USING (auth.role() = 'authenticated');

-----------------------------------------------------------
-- 6. DAILY INVENTORY & 7. DAILY INVENTORY ITEMS
-----------------------------------------------------------
CREATE POLICY "Anyone can read daily_inventory" ON public.daily_inventory FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can insert daily_inventory" ON public.daily_inventory FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Anyone can update daily_inventory" ON public.daily_inventory FOR UPDATE USING (auth.role() = 'authenticated');
-- Only admins can delete
CREATE POLICY "Admins can delete daily_inventory" ON public.daily_inventory FOR DELETE USING (public.is_admin());

CREATE POLICY "Anyone can read daily_inventory_items" ON public.daily_inventory_items FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can insert daily_inventory_items" ON public.daily_inventory_items FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Anyone can update daily_inventory_items" ON public.daily_inventory_items FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can delete daily_inventory_items" ON public.daily_inventory_items FOR DELETE USING (auth.role() = 'authenticated');

-----------------------------------------------------------
-- 8. REPORTS & 9. REPORT ITEMS (Immutable Snapshots)
-----------------------------------------------------------
-- NOTE: Reports are generated by triggers/RPCs. Admins can manage them.
CREATE POLICY "Anyone can read reports" ON public.reports FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can update reports" ON public.reports FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admins can insert reports" ON public.reports FOR INSERT WITH CHECK (public.is_admin());

CREATE POLICY "Anyone can read report_items" ON public.report_items FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can update report_items" ON public.report_items FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admins can insert report_items" ON public.report_items FOR INSERT WITH CHECK (public.is_admin());

-----------------------------------------------------------
-- 10. NOTIFICATIONS
-----------------------------------------------------------
CREATE POLICY "Users can read own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id OR user_id IS NULL);

-----------------------------------------------------------
-- 11. AUDIT LOGS
-----------------------------------------------------------
-- NOTE: Audit logs are INSERT-only via triggers. Only Admins can view them.
CREATE POLICY "Admins can read audit_logs" ON public.audit_logs FOR SELECT USING (public.is_admin());
